"""test auto migration

Revision ID: 6a88f53650de
Revises: 001
Create Date: 2025-11-04 22:10:23.012194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a88f53650de'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapter_feedback', 'completion_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('scenario_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('scenarios_job_id_fkey', 'scenarios', type_='foreignkey')
    op.drop_constraint('scenarios_level_id_fkey', 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'level_id')
    op.drop_column('scenarios', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenarios', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scenarios_level_id_fkey', 'scenarios', 'user_level', ['level_id'], ['level_id'])
    op.create_foreign_key('scenarios_job_id_fkey', 'scenarios', 'jobs', ['job_id'], ['job_id'])
    op.alter_column('scenario_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chapter_feedback', 'completion_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
