"""Add PostLike model for post likes feature

Revision ID: 79780c309bf5
Revises: cfa392bae905
Create Date: 2025-11-15 00:30:54.233976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79780c309bf5'
down_revision = 'cfa392bae905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_like')
    )
    op.create_index(op.f('ix_post_likes_like_id'), 'post_likes', ['like_id'], unique=False)
    # users.role 타입 변경은 이미 적용된 상태이므로 주석 처리
    # op.alter_column('users', 'role',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=10),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_likes_like_id'), table_name='post_likes')
    op.drop_table('post_likes')
    # users.role 타입 변경은 이미 적용된 상태이므로 주석 처리
    # op.alter_column('users', 'role',
    #            existing_type=sa.String(length=10),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
