"""Add is_deleted field to Reply model for soft delete

Revision ID: cfa392bae905
Revises: eaef263d93d0
Create Date: 2025-11-15 00:24:40.668521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa392bae905'
down_revision = 'eaef263d93d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # is_deleted 필드 추가 (기본값 False)
    op.add_column('replies', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # users.role 타입 변경은 이미 적용된 상태이므로 주석 처리
    # op.alter_column('users', 'role',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=10),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'is_deleted')
    # users.role 타입 변경은 이미 적용된 상태이므로 주석 처리
    # op.alter_column('users', 'role',
    #            existing_type=sa.String(length=10),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
