"""Add community features: pinned posts, nested replies, user roles

Revision ID: eaef263d93d0
Revises: 5289b9b0c016
Create Date: 2025-11-14 17:32:08.148545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaef263d93d0'
down_revision = '5289b9b0c016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('replies', sa.Column('parent_reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'replies', 'replies', ['parent_reply_id'], ['reply_id'])
    op.alter_column('scenario_progress', 'speech_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # Handle enum type and role column
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if role column already exists
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    role_exists = 'role' in users_columns
    
    if not role_exists:
        # Check if enum type exists
        enum_exists = conn.execute(sa.text(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
        )).scalar()
        
        if enum_exists:
            # Check if enum is used in other tables (besides users which we're about to add)
            enum_usage = conn.execute(sa.text("""
                SELECT COUNT(*) FROM information_schema.columns 
                WHERE udt_name = 'userrole' AND table_name != 'users'
            """)).scalar()
            
            # Check existing enum values
            enum_values = conn.execute(sa.text("""
                SELECT enumlabel FROM pg_enum 
                WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'userrole')
                ORDER BY enumsortorder
            """)).fetchall()
            enum_values_list = [row[0] for row in enum_values]
            
            # If enum has uppercase values, we need to update them to lowercase
            if 'USER' in enum_values_list or 'ADMIN' in enum_values_list:
                # Update existing data first
                op.execute(sa.text("ALTER TABLE users ALTER COLUMN role TYPE text"))
                op.execute(sa.text("UPDATE users SET role = 'user' WHERE role = 'USER'"))
                op.execute(sa.text("UPDATE users SET role = 'admin' WHERE role = 'ADMIN'"))
                # Drop and recreate enum with lowercase values
                op.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE"))
                op.execute(sa.text("CREATE TYPE userrole AS ENUM ('user', 'admin')"))
                op.execute(sa.text("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole"))
            elif 'user' in enum_values_list or 'admin' in enum_values_list:
                # Enum already has lowercase values, just use it
                pass
            else:
                # Create enum type with lowercase values
                op.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE"))
                op.execute(sa.text("CREATE TYPE userrole AS ENUM ('user', 'admin')"))
        else:
            # Create enum type with lowercase values
            op.execute(sa.text("CREATE TYPE userrole AS ENUM ('user', 'admin')"))
        
        # Add role column
        op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', name='userrole', create_type=False), nullable=True))
        op.execute(sa.text("UPDATE users SET role = 'user'::userrole WHERE role IS NULL"))
        op.alter_column('users', 'role', nullable=False)
    else:
        # Role column already exists, check if we need to update enum values
        enum_exists = conn.execute(sa.text(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
        )).scalar()
        
        if enum_exists:
            enum_values = conn.execute(sa.text("""
                SELECT enumlabel FROM pg_enum 
                WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'userrole')
                ORDER BY enumsortorder
            """)).fetchall()
            enum_values_list = [row[0] for row in enum_values]
            
            # If enum has uppercase values, update to lowercase
            if 'USER' in enum_values_list or 'ADMIN' in enum_values_list:
                # Temporarily cast to text, update, then cast back
                op.execute(sa.text("""
                    ALTER TABLE users ALTER COLUMN role TYPE text;
                    UPDATE users SET role = 'user' WHERE role = 'USER';
                    UPDATE users SET role = 'admin' WHERE role = 'ADMIN';
                """))
                # Recreate enum and column
                op.execute(sa.text("DROP TYPE IF EXISTS userrole CASCADE"))
                op.execute(sa.text("CREATE TYPE userrole AS ENUM ('user', 'admin')"))
                op.execute(sa.text("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop enum type if it exists and is not used elsewhere
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole')"
    )).scalar()
    if result:
        # Check if enum is used in other tables
        enum_usage = conn.execute(sa.text("""
            SELECT COUNT(*) FROM information_schema.columns 
            WHERE udt_name = 'userrole'
        """)).scalar()
        if enum_usage == 0:
            op.execute(sa.text("DROP TYPE IF EXISTS userrole"))
    op.alter_column('scenario_progress', 'speech_metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_column('replies', 'parent_reply_id')
    op.drop_column('posts', 'is_pinned')
    # ### end Alembic commands ###
